export const posts = [
  {
    title: 'HR interview questions?',
    description: 'Let\' review the HR interview questions together to answer them wisely.',
    author: 'Mohsen Shafiei Tafreshi',
    time: '6 Minutes Reading',
    date: '25 June 2019',
    content: [
      `
      HR interview is one of most important part of the interview process. You can
      be a real tech rock star but, if you don't know anything about soft skills
      and HR interview question maybe you miss a good job opportunity in your life. Here
      is the list of the most important HR interview questions. I have gathered
      these questions from different websites personally to help me in my career
      as a frontend developer and right now I want to share them with you. Here we go:
      `,
      `1- Tell me about yourself?`,
      `2- Why do you want to work for this company?`,
      `3- Do you consider yourself successful?`,
      `4- Are you willing to travel?`,
      `5- What are your salary expectation`,
      `6- What would you consider your greatest strengths & weakness?`,
      `7- What motivates you?`,
      `8- Tell me about your dream job.`,
      `9- Why did you leave your last job?`,
      `10- What experience do you have in this field?`,
      `11- What do co-workers say about you?`,
      `12- Why should we hire you?`,
      `13- Are you a team player?`,
      `14- What is your philosophy towards work?`,
      `15- What have you learned from mistakes on the job?`,
      `16- Describe your management style.`,
      `17- How would you know you were successful on this job?`,
      `18- Are you willing to work overtime? Prepare for night shift and work on Weekends?`,
      `19- What will you do if you don’t get this position?`,
      `20- What have you done to improve your knowledge in the last year?`,
      `21- How would you be an asset to this company?`,
      `22- How long would you expect to work for us in case you are hired?`,
      `23- Describe your ability to work under pressure.`,
      `24- Tell me about a problem you had with a supervisor.`,
      `25- Why do you think you would do well at this job?`,
      `26- What irritates you about co-workers?`,
      `27- Do your skills match this job or another job more closely?`,
      `28- What has disappointed you about work?`,
      `29- If you were hiring a manager for this job, what would you look for?`,
      `30- What role do you tend to play in a team?`,
      `31- What was the most difficult decision for you made?`,
      `32- Are you willing to make sacrifices for this company?`,
      `33- What are the qualities do you look for in a boss?`,
      `34- Are you applying to other companies as well?`,
      `35- Do you know anyone who works in our company?`,
      `36- How do you propose to compensate for your lack of experience?`,
      `37- Have you ever worked in a job that you hated?`,
      `38- What would your previous supervisor say your best point is?`,
      `39- What is the most challenging thing about working with you?`,
      `40- What suggestion/s have you made in your previous employment that was implemented?`,
      `41- Would you rather be liked or feared?`,
      `42- How do you cope with stress?`,
      `43- Would you rather work for money or job satisfaction?`,
      `44- Describe your work policy ethics.`,
      `45- What was your biggest challenge with your previous boss?`,
      `46- Do you enjoy working as part of a team?`,
      `47- Why do you think you deserve this job?`,
      `48- Has anything ever irritated you about people you’ve worked with?`,
      `49- Do you have any questions for me?`,
      `50- Describe an ideal workplace for you.`,
      `51- Tell me about a time when you didn’t follow policy or had to deviate from policy.`,
      `52- Do you lie?`,
      `53- Do you have any questions for me?`,
      `54- Can you tell me about your background?`,
      `55- Can you talk me through your CV up to your current role?`,
      `56- Do you prefer working with others or alone?`,
      `57- How did you find our company culture?`,
      `58- What are your thoughts of working for our business?`,
      `59- Why did you decide to move to a new role?`,
      `60- What were the best, and worst, aspects of working for us?`,
      `61- Based on what you know about us, what could we be doing more efficiently?`,
      `62- If God was outside the interview room, what are the three  wishes you would ask from him?`,
      `63- What are the most important rewards you expect to gain from your career?`,
      `64- Give me an example of a time when you were able to successfully communicate
        with another person even when that individual may not have personally linked you (or vice versa).
      `,
      `65- Please list three areas you feel have opportunities for improvement?`,
      `66- How would you tackle the first 90 days at this job?`,
      `67- What two or three things are most important to you in your job?`,
      `68- What do you feel about diversity in the workplace ?  Do you think it is important ?`,
      `69- Tell me the difference between good and exceptional?`,
      `70- Would you consider yourself an organized person?`,
      `71- Do you consider yourself overqualified for this position?`,
      `72- Describe what qualities would you like to see in a supervisor?`,
      `73- What is more important to you, the money or the work?`,
      `74- What can you contribute to this company? Explain how you would be an asset to this company?`,
      `75- What challenges are you looking for in a position?`,
      `76- What were your reasons for selecting your college or university?`,
      `77- How will the academic program and course work you’ve taken benefit your career?`,
      `78- Which college classes or subjects did you like best? why?`,
      `79- Describe the type of professor that has created the most beneficial learning experience for you?`,
      `80- Do you think that your grades are an indication of your academic achievement?`,
      `81- What plans do you have for continued study?  An advanced degree?`,
      `82- How do you think you will compensate for your lack of experience?`,
      `83- Assuming that you are selected, what will be your strategy for next 60 days?`,
      `84- Do you think, you are overqualified for this position?`,
      `85- I see there is some gap in your work history. Why?`,
      `86- If you are allowed to change one thing about your last job, what would it be?`,
      `87- What do you do to improve your knowledge?`,
      `88- How do you rate your communication skills?`,
      `89- Have you ever fired anyone? How would you go about firing a person, if required?`,
      `90- Is there any particular kind of person you can not work with?`,
      `91- What qualities would you look for in your senior?`,
      `92- Will you be happy to re-locate, if required?`,
      `93- Do you have any blind spots?`,
      `94- Have you ever given a feedback on anyone's poor performance? If yes How?`,
      `95- Has there been any chance when your boss was not very happy with your performance?`,
      `96- May I contact your present employer for a reference?`,
      `97- How could you have improved your career progress?`,
      `98- Who has inspired you in your life and why?`,
      `99- Give some examples of your teamwork.`,
      `100- Tell me about a time you worked well as part of a team.`,
      `101- What role have you played in team situations?`,
      `102- What strategies would you use to motivate your team?`,
      `103- What would you contribute to our team culture?`,
      `104- How would you handle it if there was a problem with a member of your team not doing their fair share or work?`,
      `105- If you knew a manager is 100 percent wrong about something, how would you handle it?`,
      `106- Describe yourself in one word?`,
      `107- What is the difference between confidence and overconfidence?`,
      `108- What is the difference between smart work and hard work?`,
      `109- What is your favorite book?`,
      `110- As you said, internet surfing is your hobby. Which site do you surf mostly?`,
      `111- Do you have any reference?`,
      `112- On a scale of one to ten, rate me as an interviewer?`,
    ],
    link: '',
  },
];
